### ISSUE TITLE
Mejorar la usabilidad de la gestión de lugares

### ISSUE THREAD

**Issue by viktorKhan** [sao-albacete/aoa#11]
Mejorar la usabilidad del CRUD de lugares y su selección.
- Cuando se de de alta un nuevo lugar desde el alta de cita, actualizar el listado de lugares de la tabla para que se pueda seleccionar en ese mismo momento.
- En la pantalla que muestra todos los lugares, incorporar un mapa en el que aparezcan todos los lugares datos de alta hasta ahora y que al pulsar en ellos se muestra toda su información (UTM, municipio, comarca y quizás otros datos como número de citas).
- Mejorar el alta de lugares, tanto desde la pantalla general como desde el popup.
- Usar paginación desde servidor en la página general de lugares

**Comment by Terekab** [comment]
<h5>Información sobre las UTM.</h5> Añadir documento informativo para que se informe en la página de "localización-->Cuadrículas UTM". Se puede poner en esa página, bien en ayuda o en la misma página.

**Comment by viktorKhan** [comment]
Se va a proceder a abrir una nueva tarea para este fin.
