### ISSUE TITLE
Pequeños errores encontrados en README.md

### ISSUE THREAD

**Issue by numeropi** [sao-albacete/aoa#124]
Para instalar la versión 5.3 de PHP -> debería poner la 5.6 según lo instalado a continuación
para ellos,  -> para ello

CREATE USER 'username'@'localhost' IDENTIFIED BY 'password';
cambiar a
CREATE USER 'user'@'localhost' IDENTIFIED BY 'password';

ya que es el usado luego en el  app/Config/database.php por defecto

Quizás falta el paso donde se explica que debería clonar el repositorio en /var/www/html/aoa/app/webroot ?
o en todo caso cuando se configura el sitio en apache, indicar que ahí va el directorio donde se tenga el código PHP.

añadir en el aoa.conf un
ErrorLog /var/www/html/aoa/app/tmp/logs/aoa-errors.log

Falta cambiar el .htaccess para que apunte bien al la app en el parámetro RewriteBase
, porque si no, se genera el siguiente error al ejecutar la app desde el navegador:

[Mon May 25 18:04:03.701408 2020] [core:error] [pid 9162] [client 127.0.0.1:60520] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace., referer: http://local.anuario.albacete.org/
[Mon May 25 18:04:03.701425 2020] [core:debug] [pid 9162] core.c(3690): [client 127.0.0.1:60520] AH00121: r->uri = /path/to/cake/app/index.php, referer: http://local.anuario.albacete.org/
[Mon May 25 18:04:03.701436 2020] [core:debug] [pid 9162] core.c(3697): [client 127.0.0.1:60520] AH00122: redirected from r->uri = /path/to/cake/app/index.php, referer: http://local.anuario.albacete.org/
[Mon May 25 18:04:03.701461 2020] [core:debug] [pid 9162] core.c(3697): [client 127.0.0.1:60520] AH00122: redirected from r->uri = /path/to/cake/app/index.php, referer: http://local.anuario.al

quizás poner como instalar composer:
curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer

y desde la carpeta del código:
sudo ./composer.phar install

Poner también que se cambie renombre a core.php

También tuve que cambiar el path en 
Cache::config('_cake_core_', array(
conteniendo  /var/www/html/aoa/app/tmp/cache/

**Comment by numeropi** [comment]
Quizás todas las referencias a /var/www/html/aoa/  se podrían cambiar por <CARPETA_CODIGO>
así se evitan errores si alguien(como es mi caso) tiene la carpeta de trabajo git en otro directorio.

**Comment by viktorKhan** [comment]
He introducido algunas modificaciones en el fichero README.md. Revísalo si quieres y si crees que hay que cambiar alguna otra cosa, por favor, abre otra issue.

Gracias por la aportaciones.

**Comment by numeropi** [comment]
Faltaría Poner también que se cambie renombre a core.php  (está solo el default)

También tuve que cambiar el path en
Cache::config('cake_core', array(
conteniendo /var/www/html/aoa/app/tmp/cache/   (o a la carpeta cache de nuestro...)
