### ISSUE TITLE
Nueva categoría en la tabla clase reproducción

### ISSUE THREAD

**Issue by Terekab** [sao-albacete/aoa#138]
Se añade  nueva categoría en la tabla "clase_reproducción":
- tipoCría= No cría
- idtipoCria=1
- codigo= NS
- descripcion= Individuos observados en invieno o primavera con signos de reproducción, machos con cantos territoriales, pero sabemos con seguridad que no crían.

**Comment by viktorKhan** [comment]
Insertado registro en base de datos.
