### ISSUE TITLE
Mostrar correctamente si una cita es seleccionada

### ISSUE THREAD

**Issue by viktorKhan** [sao-albacete/aoa#5]
Sigue sin estar resuelta la incidencia 58. Ocurre en la cita 12481, chorlito dorado, 30 aves el 7-12-14 en Llanos de Riachuelos.

**Comment by viktorKhan** [comment]
Necesito un recordatorio de cúal es el problema con esta cita.

**Comment by Terekab** [comment]
Esta cita es seleccionada, pero en el <b>criterio de selección de la cita</b> pone "Cita no seleccionada", con lo cual algo falla.

**Comment by viktorKhan** [comment]
No hay nuevas noticias sobre esta incidencia. En caso de que vuelva a suceder, se abrirá una nueva incidencia.
