### ISSUE TITLE
Añadir marca de agua a todas las imágenes subidas por los usuarios

### ISSUE THREAD

**Issue by viktorKhan** [sao-albacete/aoa#74]
Cada vez que un usuario suba una imagen al anuario, habrá que añadirle una marca de agua en la que se muestre:
- El nombre completo del usuario que sube la foto
- La plataforma a través de la cual se ha subido la foto, en este caso, Anuario Ornitológico de Albacete.

Por ejemplo, si el nombre del autor fuera John Doe, en la foto debería aparecer:

> Autor: John Doe
> Fuente: Anuario Ornitológico de Albacete

Este sería un ejemplo:
![image](https://user-images.githubusercontent.com/4686378/77231630-89d92100-6b9c-11ea-88ae-8d88ab7a802a.png)

También sería necesario crear un script para añadir la marca de agua a todas las fotos existentes actualmente.

**Comment by Terekab** [comment]
Si se pudiera también añadir el logotipo de la SAO, aunque fuera muy pequeño, quedaría mejor, pero no es imprescindible.

**Comment by viktorKhan** [comment]
Parece que se puede utilizar la propia libraría GD para hacerlo -> http://programmerblog.net/watermark-images-using-php/

**Comment by viktorKhan** [comment]
Después de implementar la función para insertar la marca de agua a las fotos, estos son algunos ejemplos del resultado:
![image](https://user-images.githubusercontent.com/4686378/78969236-c6969900-7b06-11ea-9486-e842984a08ec.png)
![image](https://user-images.githubusercontent.com/4686378/78969257-ce563d80-7b06-11ea-8a5d-92e3a316a447.png)
![image](https://user-images.githubusercontent.com/4686378/78969271-d615e200-7b06-11ea-89f7-6d3609a988ff.png)
![image](https://user-images.githubusercontent.com/4686378/78969287-ddd58680-7b06-11ea-9b1d-fe2d8c5cc5a1.png)
![image](https://user-images.githubusercontent.com/4686378/78969304-e928b200-7b06-11ea-98f2-b7ef89af0718.png)
![image](https://user-images.githubusercontent.com/4686378/78969311-f0e85680-7b06-11ea-8b4e-74ec5abf8385.png)
Como véis, en el último caso, no se aprecia más que el logo de la SAO. Quizás añadiendo un fondo neutro y cambiando las letras a negro se mejoraría la visibilidad, ¿qué opináis @dcmataab @Terekab ?

**Comment by Terekab** [comment]
Pues está muy bien. 
Como tu dices, con fondo neutro y letras en negro quedaría mejor. También se podría utilizar una mask, es un halo alrededor de las letras, o un borde blanco, pero cualquiera de estas opciones están bien.
Tipo así
![imagen](https://user-images.githubusercontent.com/10784270/78970628-0ad76880-7b0a-11ea-8225-e1de9dbccfb0.png)

Y en lugar de autor se puede utilizar también el símbolo de copyright ©, pero bueno lo que veáis.

**Comment by viktorKhan** [comment]
Vale, intento ponerle un fondo neutro.

Por otro lado, todos los contenidos del anuario están bajo esta licencia https://creativecommons.org/licenses/by-nc-nd/4.0/ por lo que no podemos usar ninguna referencia a licencias copyright https://www.tilomotion.com/blog/licencias-que-todos-debemos-aprender-copyright-copyleft-y-creative-commons/

**Comment by viktorKhan** [comment]
¿Qué tal así?
![image](https://user-images.githubusercontent.com/4686378/78973347-0150ff00-7b10-11ea-859a-72d8b45c46b3.png)
![image](https://user-images.githubusercontent.com/4686378/78973366-07df7680-7b10-11ea-932e-fa79e4530be9.png)

**Comment by Terekab** [comment]
> 
> 
> Vale, intento ponerle un fondo neutro.
> 
> Por otro lado, todos los contenidos del anuario están bajo esta licencia https://creativecommons.org/licenses/by-nc-nd/4.0/ por lo que no podemos usar ninguna referencia a licencias copyright https://www.tilomotion.com/blog/licencias-que-todos-debemos-aprender-copyright-copyleft-y-creative-commons/

Es verdad, lo de la licencia no me acordaba.
Por mi está bien.

**Comment by dcmataab** [comment]
Yo cambiaría la frase de "Fuente: Anuario...." por la dirección web del anuario. También haría la letra más pequeña. Por lo demás, la última versión con letras en negro y marco me parece bien.
Por otro lado, ¿La posición de las letras va a ser siempre la misma o se puede cambiar?

**Comment by viktorKhan** [comment]
> Yo cambiaría la frase de "Fuente: Anuario...." por la dirección web del anuario.
Si llevas razón, igual tiene más sentido poner la URL.

> También haría la letra más pequeña.
Ahora mismo tiene un tamaño 14, la puedo bajar a tamaño 11

> ¿La posición de las letras va a ser siempre la misma o se puede cambiar?
Siempre será la misma

**Comment by viktorKhan** [comment]
Aquí tenéis el resultado final:
![image](https://user-images.githubusercontent.com/4686378/79069980-b16e6580-7cd2-11ea-8499-7df64e8e3feb.png)
