### ISSUE TITLE
Actualizar enlace a la ficha de rarezas de SEO/BirdLife

### ISSUE THREAD

**Issue by Terekab** [sao-albacete/aoa#85]
El enlace que aparece cuando insertas una cita que es considerada rareza nacional por SEO/BirdLife aparece roto. Habría que actualizarlo. 
Este es el nuevo enlace [https://www.seo.org/wp-content/uploads/2016/03/Ficha_Rarezas_CRSEO.pdf](url)

![imagen](https://user-images.githubusercontent.com/10784270/78104235-1da5bb00-73ef-11ea-9261-6791551d02cc.png)

**Comment by viktorKhan** [comment]
Corregido.
