### ISSUE TITLE
Descarga de datos 1

### ISSUE THREAD

**Issue by dcmataab** [sao-albacete/aoa#90]
He comprobado que al descargar datos en .xls el máximo de datos es de 1000. ¿Se podría aumentar el máximo?

**Comment by Terekab** [comment]
Creo que se puso un límite de 1000 para evitar que se colgara la BBDD.

**Comment by viktorKhan** [comment]
Puse ese límite para evitar problemas de rendimiento de la aplicación o incluso que se quede colgado el servidor. Si tienes gran cantidad de datos siempre se puede filtar por fechas y sacar citas por intervalos de tiempo o usando otros criterios para recudir el número de resultados.
