### ISSUE TITLE
Descarga de la Lista de aves

### ISSUE THREAD

**Issue by dcmataab** [sao-albacete/aoa#93]
La lista de aves ahora se descarga si entras en la pestaña de metodología. Creo que lo suyo es que se pueda descargar en la misma pantalla de la lista de aves. Yo creo que arriba, en un lugar visible sería el mejor sitio.

**Comment by Terekab** [comment]
Sí, cuesta mucho encontrarla y poca gente sabrá que está ahí. La ubicación que dices está bien. Y el recuadro "Metodología" mejora la izquierda, lo que está a la derecha parece que no se ve por la inercia de mirar siempre a la izquierda.

**Comment by viktorKhan** [comment]
Este es el aspecto que tendrá la pantalla después de los cambios:
![image](https://user-images.githubusercontent.com/4686378/79640513-491bfa00-8192-11ea-95db-ad317112f2a6.png)

**Comment by Terekab** [comment]
Perfecto
