### ISSUE TITLE
Añadir campos para precisar los datos

### ISSUE THREAD

**Issue by Terekab** [sao-albacete/aoa#95]
Para mejorar la toma de datos, estaría bien crear unos campos nuevos para facilitar luego consultas. Estos datos, se suelen poner en observaciones, y luego para hacer búsquedas se pierden.
Serían estos campos:
- Dormidero
- Colonia de cría
- En migración activa
- Sedimentados.

Y también, cuando se indique el número de aves poder elegir una de estas opciones

- Número exacto
- Conteo preciso
- Estima
- Número aproximado

**Comment by viktorKhan** [comment]
@Terekab @dcmataab aprovecho esta issue para incluir también los criterios?
- electrocutado
- atropellado

**Comment by Terekab** [comment]
Yo creo que sí, puede añadirse ahí como dijimos.

**Comment by viktorKhan** [comment]
Sobre estos atributos:
-     Número exacto
-     Conteo preciso
-     Estima
-     Número aproximado
¿Sin excluyentes? Es decir, ¿sólo se puede elegir uno de ellos o varios a la vez? ¿Por defecto dejo marcado "Número exacto"?

**Comment by viktorKhan** [comment]
Respuesta de @Terekab 

> Sí, excluyentes. Y número exacto por defecto

**Comment by viktorKhan** [comment]
Como aclaración, el concepto "sedimentado" según @Terekab se refiere a:

> Sedimentados es un grupo de aves en migración que permanecen descansando en un mismo sitio un tiempo. Por ejemplo un grupo grande de milanos que los ves varios días

**Comment by viktorKhan** [comment]
Como parte de esta tarea, he detectado que al exportar citas, si las observaciones no tenían contenido, en algunos casos se exportaba esto "<p><br/></p>". Esto es debido al plugin summernote que usamos para el texto enriquecido. Para solucionar esto se han aplicado dos cambios:

1. Sólo guardar contenido del campo observaciones cuando se haya escrito algo, para ello hacemos uso de este método https://summernote.org/deep-dive/#isempty
2. Al exportar el texto de las observaciones a excel, se aplica la función de PHP https://www.php.net/manual/es/function.strip-tags.php para no exportar el texto en formato HTML
