### ISSUE TITLE
Crear un nuevo apartado para añadir referencias a una cita

### ISSUE THREAD

**Issue by viktorKhan** [sao-albacete/aoa#98]
## Escenario actual
En ocasiones un usuario desea añadir un enlace a la cita, para ello, suelen usar el campo descripción, sin embargo, al añadir el enlace en este campo se guarda como un texto y no se renderiza como un enlace al visualizar la cita.

## Escenario esperado
Crear una nueva sección en la pantalla de alta / edición de citas para poder añadir enlaces / referencias en las citas y que éstas puedan ser renderizadas como enlaces al visualizar la cita.

**Comment by viktorKhan** [comment]
Estoy barajando, en lugar de añadir una nueva sección para referencias, simplemente añadir un editor "wysiwyg" para poder formatear las observaciones. 
Por ejemplo con esta librería:
https://mindmup.github.io/bootstrap-wysiwyg/

**Comment by viktorKhan** [comment]
La librería indicada en el comentario anterior no funciona bien.

Probando esta -> https://summernote.org/

**Comment by viktorKhan** [comment]
El campo observaciones con el editor de texto enriquecido quedaría así:
![image](https://user-images.githubusercontent.com/4686378/79643053-52f92980-81a1-11ea-9fd6-74232d8d3acd.png)

**Comment by viktorKhan** [comment]
Quedaría de esta forma en la página de visualización de citas:
![image](https://user-images.githubusercontent.com/4686378/79643135-baaf7480-81a1-11ea-9572-f9296fc5b4bf.png)

**Comment by viktorKhan** [comment]
Al permitir la introducción y renderización de HTML es necesario aplicar securidad para evitar ataques Cross-Site Scripting (XSS). Mirar este enlace de buenas práctias generales para PHP -> https://paragonie.com/blog/2017/12/2018-guide-building-secure-php-software#secure-php-xss
Y esta herramienta -> http://htmlpurifier.org/

**Comment by Terekab** [comment]
Por mi bien, es junto lo que queríamos, que puedas poner enlaces externos, y sí además formateas texto, para destacar algo pues mejor. 

> 
> Quedaría de esta forma en la página de visualización de citas:
> ![image](https://user-images.githubusercontent.com/4686378/79643135-baaf7480-81a1-11ea-9572-f9296fc5b4bf.png)
